feat: added method for returning full plan object
5G-ERA/era-5g-client pull request #34
Opened 2023-05-12 07:12 UTC by adrianLIrobotics

I added another method for returning the whole plan for later parsing in the AC/AS.

Many thanks!

2023-05-12 08:10 UTC, Kapim requested changes
The gateway_get_full_plan is almost identical to the gateway_get_plan (the only difference is that the latter only returns one ActionPlanID). Can you rewrite the gateway_get_plan method to utilize the gateway_get_full_plan?

2023-05-12 08:13 UTC, Kapim commented on era_5g_client/client.py
> +    def gateway_get_full_plan(self, taskid: str, resource_lock: bool, robot_id: str) -> str:
The method does not return a string but a response (a dict probably?). Moreover, should it return the whole response? I think it would be better if we could create a data class that will describe the plan and return it (similar to MiddlewareInfo in https://github.com/5G-ERA/era-5g-client/blob/main/era_5g_client/dataclasses.py).

2023-05-17 11:52 UTC, adrianLIrobotics commented
Hello Michal, Bartosz, can you check the dataclasses file and the parser_middleware_plan_info in client.py

The idea is that the response from the middleware will be translated into a dataclass object defined with the middleware response. Please do not merge as i still want to do proper testing :)

2023-05-18 09:50 UTC, Artonus requested changes
@adrianLIrobotics, the logic looks good to me, but please correct the changes mentioned in the comments. On top of this, please make sure to address the changes that @Kapim has requested. 
Thanks!

2023-05-18 09:50 UTC, Artonus commented on era_5g_client/client.py
> +                    rosTopicsPub.append(MiddlewareRosTopicModel(topicPubData["name"],topicPubData["type"],topicPubData["description"],topicPubData["enabled"] ))
Can a constructor be created in the `dataclass` to accept the dictionary? Then in this constructor, we could extract all the necessary data. It would make this section of the code much cleaner and easy to read.

2023-05-18 09:50 UTC, Artonus commented on era_5g_client/dataclasses.py
> +    ReplanActionPlannerLocked: bool
@adrianLIrobotics I believe that these names don't follow the correct python name format, and this is why you can't get the CI build passing. 
@Kapim can you confirm it?

2023-05-18 10:49 UTC, Kapim requested changes
I have added a few more comments

2023-05-18 10:49 UTC, Kapim commented on era_5g_client/client.py
> +        for x in range(0,len(actionSequenceData)):
It is more "Pythonic" to iterate through iterable like this `for action in actionSequenceData:`

2023-05-18 10:49 UTC, Kapim commented on era_5g_client/client.py
> +            for y in range(0,len(serviceData)):
same as above, please use `for service in serviceData:`

2023-05-18 10:49 UTC, Kapim commented on era_5g_client/client.py
> +                for z in range(0,len(topicPubData)):
Same as above. Moreover, is the topicPubData a list or something? Because inside the cycle, you are not iterating through it and only extracting the data from it.

2023-05-18 10:49 UTC, Kapim commented on era_5g_client/client.py
> +                    rosTopicsPub.append(MiddlewareRosTopicModel(topicPubData["name"],topicPubData["type"],topicPubData["description"],topicPubData["enabled"] ))
I think we should keep the constructor as it is but either implement some "from_dict" static method which will instantiate the object from the dictionary or use, e.g., the dacite.from_dict method to create the instance `rosTopicPub.append(dacite.from_dict(data_class=MiddlewareRosTopicModel, data=topicPubData))`. @ZdenekM, what would be the best way to instantiate the dataclass model here?

2023-05-18 10:49 UTC, Kapim commented on era_5g_client/client.py
> +                    rosTopicsPub.append(MiddlewareRosTopicModel(topicPubData["name"],topicPubData["type"],topicPubData["description"],topicPubData["enabled"] ))
But I definitely agree with @Artonus that we should make this section more cleaner

2023-05-18 10:49 UTC, Kapim commented on era_5g_client/dataclasses.py
> +    ReplanActionPlannerLocked: bool
Yes, you should follow the PEP 8 style guide, i.e., the variable names should be snake_case formatted (lowercase with words separated by underscores). Only classes should use the PascalCase format.

2023-05-19 06:28 UTC, ZdenekM commented on era_5g_client/client.py
> +                    rosTopicsPub.append(MiddlewareRosTopicModel(topicPubData["name"],topicPubData["type"],topicPubData["description"],topicPubData["enabled"] ))
@Kapim If you need `from_dict` method for dataclasses, takes a look here: https://github.com/s-knibbs/dataclasses-jsonschema/ - pretty cool, I used it in arcor2.

2023-05-19 06:29 UTC, ZdenekM commented on era_5g_client/client.py
> +        for x in range(0,len(actionSequenceData)):
Also, `action_list = []` should have a type annotation.

2023-05-19 06:30 UTC, ZdenekM commented on era_5g_client/client.py
> +            for y in range(0,len(serviceData)):
Add type annotation to `service_list = []`.

2023-05-19 06:33 UTC, ZdenekM commented
@adrianLIrobotics Before making a commit, please run `./pants fmt ::` (it will sort imports and format the code), then `./pants lint ::` (it will run flake8 and black tools and report possible problems), and finally `./pants check ::` (runs mypy tool, which performs static analysis of the code and types). Thanks!

2023-05-19 06:36 UTC, ZdenekM commented on era_5g_client/client.py
> +                    rosTopicsPub.append(MiddlewareRosTopicModel(topicPubData["name"],topicPubData["type"],topicPubData["description"],topicPubData["enabled"] ))
And because properties in a dictionary are named in the `camelCase` convention and properties in dataclasses will be in `snake_case`, we will need to convert the dictionary between those with this: https://github.com/nficano/humps.

2023-05-19 06:38 UTC, ZdenekM commented on era_5g_client/client.py
> +                    rosTopicsPub.append(MiddlewareRosTopicModel(topicPubData["name"],topicPubData["type"],topicPubData["description"],topicPubData["enabled"] ))
Hmm, I look better and it seems that there is a mix of `camelCase` and `PascalCase` (`ServiceType`).

2023-05-19 06:42 UTC, ZdenekM commented on era_5g_client/dataclasses.py
> +    ReplanActionPlannerLocked: bool
There are more problems :) But most of them can be solved by using autoformatting (`./pants fmt ::`). After passing this stage of check, there will be type checking (mypy) which will (possibly) reveal another set of problems.

![Snímek obrazovky pořízený 2023-05-19 08-40-34](https://github.com/5G-ERA/era-5g-client/assets/1199396/b82a54b6-2547-4386-8de8-8107d654b629)

2023-05-19 06:45 UTC, ZdenekM commented
@adrianLIrobotics Also, please merge commits into one so we have a clear and comprehensible history. Many thanks!

2023-09-20 08:26 UTC, Kapim commented
@adrianLIrobotics do you plan to work on this in the near future?

2024-04-23 06:28 UTC, ZdenekM commented
Closing for no activity.

2024-04-23 06:28 UTC, closed without merging