#4 Make client compatible with Reference-NetApp, #3 POST and JSON use…
5G-ERA/era-5g-client pull request #5
Opened 2023-02-22 23:05 UTC by klepo

…d in register and unregister, check if cv2.VideoWriter (DataSenderGStreamer.out) is opened, asserts after register in test client scripts, info logging in test scripts, from __future__ import annotations fix due to "results_storage: Queue[Dict[str, Any]] = Queue()"

2023-02-23 07:37 UTC, ZdenekM requested changes

2023-02-23 07:37 UTC, ZdenekM commented on era_5g_client/data_sender_gstreamer.py
> +            raise Exception("Cannot open VideoWriter pipeline")
This should not be `Exception` but some custom one.

2023-02-23 07:37 UTC, ZdenekM commented on requirements.txt
> +#opencv-contrib-python~=4.6.0.66  # for usage with GStreamer, one has to compile OpenCV with its support turned on
Maybe you comment this out for testing? In the repo, it should be there. Otherwise, mypy checking would fail.

2023-02-23 07:37 UTC, ZdenekM commented on scripts/client_gstreamer.py
> +    logging.getLogger().setLevel(logging.INFO)
What's the purpose of this? If I see it right, the logger is not used in this example.

2023-02-23 07:37 UTC, ZdenekM commented on scripts/client_http.py
> +from __future__ import annotations
Why is this needed? Mypy was happy for all versions of Python we intend to support :)

2023-02-23 07:39 UTC, ZdenekM commented
@klepo Please check these instructions: https://github.com/5G-ERA/era-5g-client#contributing-development

2023-02-23 07:50 UTC, ZdenekM commented on scripts/client_http.py
> +from __future__ import annotations
Well, this is needed for Python 3.8. For 3.9 and 3.10 it should be fine. I have to check configuration of mypy, it is probably not testing with all version of Python.

2023-02-23 11:50 UTC, Kapim requested changes

2023-02-23 11:50 UTC, Kapim commented on scripts/client_gstreamer.py
> +TEST_VIDEO_FILE = os.getenv("TEST_VIDEO_FILE", "../assets/2017_01_02_001021_s.mp4")
The path to the video file should not be there, as the test file is in a different repository. It would be better to test if the env variable is set and print an error if it's not (and close the application).

2023-02-23 11:50 UTC, Kapim commented on scripts/client_gstreamer_no_middleware.py
> +TEST_VIDEO_FILE = os.getenv("TEST_VIDEO_FILE", "../assets/2017_01_02_001021_s.mp4")
same as above

2023-02-23 11:50 UTC, Kapim commented on scripts/client_http.py
> +TEST_VIDEO_FILE = os.getenv("TEST_VIDEO_FILE", "../assets/2017_01_02_001021_s.mp4")
same as above

2023-02-23 18:29 UTC, klepo commented on requirements.txt
> +#opencv-contrib-python~=4.6.0.66  # for usage with GStreamer, one has to compile OpenCV with its support turned on
Why opencv-contrib-python and not opencv-python? We are using version opencv-python 4.6.0.3725898. So I suggest changing to opencv-python~=4.6.0.37

2023-02-23 18:32 UTC, klepo commented on scripts/client_gstreamer.py
> +    logging.getLogger().setLevel(logging.INFO)
I think it will be used in client.py in the future.

2023-02-23 18:34 UTC, klepo commented on scripts/client_gstreamer.py
> +TEST_VIDEO_FILE = os.getenv("TEST_VIDEO_FILE", "../assets/2017_01_02_001021_s.mp4")
Why should the test file be in a different repository than the test script? That doesn't make sense to me.

2023-02-23 18:43 UTC, Kapim commented on scripts/client_gstreamer.py
> +TEST_VIDEO_FILE = os.getenv("TEST_VIDEO_FILE", "../assets/2017_01_02_001021_s.mp4")
this test script is general for all netapps, but the video is specific to only reference netapp... as I wrote here: https://github.com/5G-ERA/Reference-NetApp/issues/24 we should make this script as general as possible as en example usage of the client and upload a testing script (based on this script or even this one in particular) to the Reference NetApp repository (maybe create a folder with example scripts there in the root of the repository)

2023-02-23 18:46 UTC, Kapim commented on requirements.txt
> +#opencv-contrib-python~=4.6.0.66  # for usage with GStreamer, one has to compile OpenCV with its support turned on
yes, we talked about it with @ZdenekM earlier today, we should change it to opencv-python. Unfortunatelly, PyPI does notnhavr 4.6.0.37 version (only 4.6.0.66 was released), so we should probably stick with it and try if it will work

2023-02-23 20:07 UTC, ZdenekM commented on requirements.txt
> +#opencv-contrib-python~=4.6.0.66  # for usage with GStreamer, one has to compile OpenCV with its support turned on
That's already done. Please update your fork.

2023-02-23 20:12 UTC, klepo commented on era_5g_client/data_sender_gstreamer.py
> +            raise Exception("Cannot open VideoWriter pipeline")
TODO

2023-02-23 20:13 UTC, klepo commented on scripts/client_gstreamer.py
> +TEST_VIDEO_FILE = os.getenv("TEST_VIDEO_FILE", "../assets/2017_01_02_001021_s.mp4")
OK

2023-02-24 07:23 UTC, Kapim approved these changes
Seems good to me, just a note: when the TEST_VIDEO_FILE is not set or is set to a non-existing video file, the user should be notified of the existence of the env variable, so they can set it.

2023-02-27 08:14 UTC, ZdenekM requested changes

2023-02-27 08:14 UTC, ZdenekM commented on scripts/client_http.py
> +TEST_VIDEO_FILE = os.getenv("TEST_VIDEO_FILE", "")
The same here - in my opinion, it would be better without default value.

2023-02-27 14:59 UTC, closed without merging