feat!: add init control command
5G-ERA/era-5g-client pull request #51
Opened 2023-08-17 11:26 UTC by idobes

2023-08-18 07:19 UTC, ZdenekM requested changes
Please update the version of the interface to 0.5.0 here https://github.com/5G-ERA/era-5g-client/blob/main/requirements.txt#L7

2023-08-18 13:07 UTC, ZdenekM commented
@idobes Sorry, forgot to mention you also need to update `python-default.lock` by running `./pants generate-lockfiles --resolve=python-default`.

2023-08-18 13:20 UTC, idobes commented
> @idobes Sorry, forgot to mention you also need to update `python-default.lock` by running `./pants generate-lockfiles --resolve=python-default`.

I've just found this out, too. :) It should be fixed now.

2023-08-21 08:34 UTC, ZdenekM approved these changes

2023-08-21 08:34 UTC, merged