feat: added support for the edge switchover
5G-ERA/era-5g-client pull request #71
Opened 2024-04-22 15:28 UTC by Kapim

2024-04-23 06:28 UTC, ZdenekM requested changes
Also it would be nice to squash it into one commit.

2024-04-23 06:28 UTC, ZdenekM commented on era_5g_client/client.py
> +    def netapp_address_changed(self):
Add some docstring?

2024-04-23 06:28 UTC, ZdenekM commented on era_5g_client/client.py
> +        self.switching: bool = False
Maybe make this "readonly" property? I mean like:

```python
def __init__():
    self._switching = False

@property
def switching() -> bool:
    """ You can document this and it is 'read-only'. """
    return self._switching

def netapp_address_changed(self):
    self._switching = True
    ...
```

2024-04-23 06:28 UTC, ZdenekM commented on era_5g_client/client.py
> +            finish (bool, optional): If true, the resource checker is finished and all resources are deleted from the server
outdated

2024-04-23 06:28 UTC, ZdenekM commented on era_5g_client/middleware_resource_checker.py
> +            url_changed_callback (Callable, optional): Trigered if the recieved url has changed.
received

2024-04-23 06:28 UTC, ZdenekM commented on era_5g_client/middleware_resource_checker.py
> +            print(resource_state)
remove

2024-04-23 06:28 UTC, ZdenekM commented on era_5g_client/middleware_resource_checker.py
> +        print(response)
remove

2024-04-23 06:28 UTC, ZdenekM commented on era_5g_client/middleware_resource_checker.py
> +        print(resp)
remove

2024-04-23 06:28 UTC, ZdenekM commented on tests/dummy_middleware.py
> +url = "http://localhost:5896"
Just a note: if this is going to be used for tests, the port should be random, as tests could be running in parallel.

2024-04-29 07:45 UTC, Kapim commented on era_5g_client/client.py
> +        self.switching: bool = False
ok, changed

2024-04-29 07:55 UTC, Kapim commented on era_5g_client/client.py
> +    def netapp_address_changed(self):
added

2024-04-29 07:55 UTC, Kapim commented on era_5g_client/client.py
> +            finish (bool, optional): If true, the resource checker is finished and all resources are deleted from the server
removed

2024-04-29 07:56 UTC, Kapim commented on era_5g_client/middleware_resource_checker.py
> +            url_changed_callback (Callable, optional): Trigered if the recieved url has changed.
updated

2024-04-29 07:59 UTC, Kapim commented on tests/dummy_middleware.py
> +url = "http://localhost:5896"
At the moment, it is only meant for manual testing.

2024-04-29 08:02 UTC, ZdenekM approved these changes

2024-04-29 08:03 UTC, merged